# Generated by Django 5.0.4 on 2024-04-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
